import {PolyfillMeta} from "./polyfill-meta";
import {ElementOf} from "helpertypes";

export const POLYFILL_DEALIASED_NAME = new Set([
	"es.object.assign",
	"es.object.create",
	"es.object.define-properties",
	"es.object.define-property",
	"es.object.freeze",
	"es.object.get-own-property-descriptor",
	"es.object.get-own-property-names",
	"es.object.get-prototype-of",
	"es.object.is-extensible",
	"es.object.is-frozen",
	"es.object.is-sealed",
	"es.object.is",
	"es.object.keys",
	"es.object.prevent-extensions",
	"es.object.seal",
	"es.object.set-prototype-of",
	"es.object.from-entries",
	"es.object.to-string",
	"es.object.define-getter",
	"es.object.define-setter",
	"es.object.entries",
	"es.object.get-own-property-descriptors",
	"es.object.lookup-getter",
	"es.object.lookup-setter",
	"es.object.values",
	"es.function.bind",
	"es.function.name",
	"es.array.concat",
	"es.array.flat",
	"es.array.flat-map",
	"es.array.last-index",
	"es.array.last-item",
	"es.array.copy-within",
	"es.array.every",
	"es.array.fill",
	"es.array.filter",
	"es.array.find-index",
	"es.array.find",
	"es.array.for-each",
	"es.array.from",
	"es.array.index-of",
	"es.array.is-array",
	"es.array.iterator",
	"es.array.join",
	"es.array.last-index-of",
	"es.array.map",
	"es.array.of",
	"es.array.reduce-right",
	"es.array.reduce",
	"es.array.slice",
	"es.array.some",
	"es.array.sort",
	"es.array.splice",
	"es.array.species",
	"es.array.includes",
	"es.array-buffer.constructor",
	"es.array-buffer.is-view",
	"es.array-buffer.slice",
	"es.string.at",
	"es.string.code-points",
	"es.string.match-all",
	"es.string.replace-all",
	"es.string.trim-start",
	"es.string.trim-end",
	"es.string.anchor",
	"es.string.big",
	"es.string.blink",
	"es.string.bold",
	"es.string.code-point-at",
	"es.string.ends-with",
	"es.string.fixed",
	"es.string.fontcolor",
	"es.string.fontsize",
	"es.string.from-code-point",
	"es.string.includes",
	"es.string.italics",
	"es.string.iterator",
	"es.string.link",
	"es.string.match",
	"es.string.pad-end",
	"es.string.pad-start",
	"es.string.raw",
	"es.string.repeat",
	"es.string.replace",
	"es.string.search",
	"es.string.small",
	"es.string.split",
	"es.string.starts-with",
	"es.string.strike",
	"es.string.sub",
	"es.string.sup",
	"es.string.trim",
	"es.regexp.constructor",
	"es.regexp.flags",
	"es.regexp.to-string",
	"es.number.constructor",
	"es.number.epsilon",
	"es.number.is-finite",
	"es.number.is-integer",
	"es.number.is-nan",
	"es.number.is-safe-integer",
	"es.number.max-safe-integer",
	"es.number.min-safe-integer",
	"es.number.parse-float",
	"es.number.parse-int",
	"es.number.to-fixed",
	"es.number.to-precision",
	"es.number.from-string",
	"es.map",
	"es.map.every",
	"es.map.filter",
	"es.map.find",
	"es.map.find-key",
	"es.map.from",
	"es.map.group-by",
	"es.map.includes",
	"es.map.key-by",
	"es.map.key-of",
	"es.map.map-keys",
	"es.map.map-values",
	"es.map.merge",
	"es.map.of",
	"es.map.reduce",
	"es.map.some",
	"es.map.update",
	"es.map.emplace",
	"es.weak-map",
	"es.weak-map.from",
	"es.weak-map.of",
	"es.set",
	"es.set.add-all",
	"es.set.delete-all",
	"es.set.difference",
	"es.set.every",
	"es.set.filter",
	"es.set.find",
	"es.set.from",
	"es.set.intersection",
	"es.set.join",
	"es.set.map",
	"es.set.of",
	"es.set.reduce",
	"es.set.some",
	"es.set.symmetric-difference",
	"es.set.union",
	"es.set.is-disjoint-from",
	"es.set.is-subset-of",
	"es.set.is-superset-of",
	"es.weak-set",
	"es.weak-set.from",
	"es.weak-set.of",
	"es.math.acosh",
	"es.math.asinh",
	"es.math.atanh",
	"es.math.cbrt",
	"es.math.clz32",
	"es.math.cosh",
	"es.math.expm1",
	"es.math.fround",
	"es.math.hypot",
	"es.math.imul",
	"es.math.log1p",
	"es.math.log2",
	"es.math.log10",
	"es.math.sign",
	"es.math.sinh",
	"es.math.tanh",
	"es.math.trunc",
	"es.math.clamp",
	"es.math.deg-per-rad",
	"es.math.degrees",
	"es.math.fscale",
	"es.math.iaddh",
	"es.math.imulh",
	"es.math.isubh",
	"es.math.rad-per-deg",
	"es.math.radians",
	"es.math.scale",
	"es.math.signbit",
	"es.math.umulh",
	"es.data-view",
	"es.date.now",
	"es.date.to-iso-string",
	"es.date.to-json",
	"es.date.to-primitive",
	"es.date.to-string",
	"es.promise.finally",
	"es.promise.constructor",
	"es.promise.all-settled",
	"es.promise.try",
	"es.promise.any",
	"es.symbol.constructor",
	"es.symbol.async-iterator",
	"es.symbol.has-instance",
	"es.symbol.is-concat-spreadable",
	"es.symbol.iterator",
	"es.symbol.match",
	"es.symbol.match-all",
	"es.symbol.replace",
	"es.symbol.search",
	"es.symbol.species",
	"es.symbol.split",
	"es.symbol.to-primitive",
	"es.symbol.to-string-tag",
	"es.symbol.unscopables",
	"es.symbol.description",
	"es.symbol.pattern-match",
	"es.typed-array.copy-within",
	"es.typed-array.every",
	"es.typed-array.fill",
	"es.typed-array.filter",
	"es.typed-array.find",
	"es.typed-array.find-index",
	"es.typed-array.float32-array",
	"es.typed-array.float64-array",
	"es.typed-array.for-each",
	"es.typed-array.from",
	"es.typed-array.includes",
	"es.typed-array.index-of",
	"es.typed-array.int8-array",
	"es.typed-array.int16-array",
	"es.typed-array.int32-array",
	"es.typed-array.iterator",
	"es.typed-array.join",
	"es.typed-array.last-index-of",
	"es.typed-array.map",
	"es.typed-array.of",
	"es.typed-array.reduce",
	"es.typed-array.reduce-right",
	"es.typed-array.reverse",
	"es.typed-array.set",
	"es.typed-array.slice",
	"es.typed-array.some",
	"es.typed-array.sort",
	"es.typed-array.subarray",
	"es.typed-array.to-locale-string",
	"es.typed-array.to-string",
	"es.typed-array.uint8-array",
	"es.typed-array.uint8-clamped-array",
	"es.typed-array.uint16-array",
	"es.typed-array.uint32-array",
	"es.reflect.apply",
	"es.reflect.construct",
	"es.reflect.define-property",
	"es.reflect.delete-property",
	"es.reflect.get",
	"es.reflect.get-own-property-descriptor",
	"es.reflect.get-prototype-of",
	"es.reflect.has",
	"es.reflect.is-extensible",
	"es.reflect.own-keys",
	"es.reflect.prevent-extensions",
	"es.reflect.set",
	"es.reflect.set-prototype-of",
	"es.reflect.define-metadata",
	"es.reflect.delete-metadata",
	"es.reflect.get-metadata",
	"es.reflect.get-metadata-keys",
	"es.reflect.get-own-metadata",
	"es.reflect.get-own-metadata-keys",
	"es.reflect.has-metadata",
	"es.reflect.has-own-metadata",
	"es.reflect.metadata",

	// API
	"api.constructable-stylesheets",
	"api.performance.now",
	"api.url",
	"api.form-data",
	"api.console",
	"api.base64",
	"api.blob",
	"api.request-idle-callback",
	"api.request-animation-frame",

	// CSS
	"css.object-fit",

	"xhr",
	"dom.collections.iterator",
	"dom.collections.for-each",
	"fetch",
	"intl.date-time-format",
	"intl.display-names",
	"intl.get-canonical-locales",
	"intl.list-format",
	"intl.locale",
	"intl.number-format",
	"intl.plural-rules",
	"intl.relative-time-format",
	"proxy",
	"window",
	"document",
	"element",
	"scroll-behavior",
	"get-computed-style",
	"node.contains",
	"node.parentelement",
	"queryselector",
	"document-fragment",
	"intersection-observer",
	"mutation-observer",
	"resize-observer",
	"custom-elements",
	"shadow-dom",
	"template",
	"class-list",
	"dom-token-list",
	"event.constructor",
	"event.focusin",
	"event.hashchange",
	"custom-event",
	"event-source",
	"pointer-event",
	"set-immediate",
	"web-animations",
	"global-this",
	"broadcast-channel",
	"proto",
	"focus-visible",

	// Library
	"lib.regenerator-runtime",
	"lib.systemjs"
] as const);

export const POLYFILL_ALIASES = {
	es: [
		"es.promise",
		"es.object",
		"es.function",
		"es.array",
		"es.array-buffer",
		"es.string",
		"es.data-view",
		"es.regexp",
		"es.number",
		"es.math",
		"es.date",
		"es.symbol",
		"es.collections",
		"es.typed-array",
		"es.reflect"
	],
	es2015: ["es"],
	"es.promise": ["es.promise.constructor", "es.promise.any", "es.promise.all-settled", "es.promise.finally"],
	"es.object": [
		"es.object.assign",
		"es.object.create",
		"es.object.define-getter",
		"es.object.define-setter",
		"es.object.entries",
		"es.object.from-entries",
		"es.object.get-own-property-descriptors",
		"es.object.lookup-getter",
		"es.object.lookup-setter",
		"es.object.values",
		"es.object.define-properties",
		"es.object.define-property",
		"es.object.freeze",
		"es.object.get-own-property-descriptor",
		"es.object.get-own-property-names",
		"es.object.get-prototype-of",
		"es.object.is-extensible",
		"es.object.is-frozen",
		"es.object.is-sealed",
		"es.object.is",
		"es.object.keys",
		"es.object.prevent-extensions",
		"es.object.seal",
		"es.object.set-prototype-of",
		"es.object.to-string"
	],
	"es.function": ["es.function.bind", "es.function.name"],
	"es.array": [
		"es.array.concat",
		"es.array.copy-within",
		"es.array.every",
		"es.array.flat",
		"es.array.flat-map",
		"es.array.fill",
		"es.array.filter",
		"es.array.find",
		"es.array.find-index",
		"es.array.for-each",
		"es.array.from",
		"es.array.includes",
		"es.array.index-of",
		"es.array.is-array",
		"es.array.iterator",
		"es.array.join",
		"es.array.last-index-of",
		"es.array.map",
		"es.array.of",
		"es.array.reduce",
		"es.array.reduce-right",
		"es.array.slice",
		"es.array.some",
		"es.array.sort",
		"es.array.species",
		"es.array.splice"
	],
	"es.array-buffer": ["es.array-buffer.constructor", "es.array-buffer.is-view", "es.array-buffer.slice"],
	"es.string": [
		"es.string.anchor",
		"es.string.big",
		"es.string.blink",
		"es.string.bold",
		"es.string.code-point-at",
		"es.string.ends-with",
		"es.string.fixed",
		"es.string.fontcolor",
		"es.string.fontsize",
		"es.string.from-code-point",
		"es.string.includes",
		"es.string.italics",
		"es.string.iterator",
		"es.string.link",
		"es.string.match",
		"es.string.pad-end",
		"es.string.pad-start",
		"es.string.raw",
		"es.string.repeat",
		"es.string.search",
		"es.string.small",
		"es.string.split",
		"es.string.starts-with",
		"es.string.strike",
		"es.string.sub",
		"es.string.sup",
		"es.string.trim",
		"es.string.trim-start",
		"es.string.trim-end",
		"es.string.replace-all"
	],
	"es.regexp": ["es.regexp.constructor", "es.regexp.flags", "es.regexp.to-string"],
	"es.number": [
		"es.number.constructor",
		"es.number.epsilon",
		"es.number.is-finite",
		"es.number.is-integer",
		"es.number.is-nan",
		"es.number.is-safe-integer",
		"es.number.max-safe-integer",
		"es.number.min-safe-integer",
		"es.number.parse-float",
		"es.number.parse-int",
		"es.number.to-fixed",
		"es.number.to-precision"
	],
	"es.math": [
		"es.math.acosh",
		"es.math.asinh",
		"es.math.atanh",
		"es.math.cbrt",
		"es.math.clz32",
		"es.math.cosh",
		"es.math.expm1",
		"es.math.fround",
		"es.math.hypot",
		"es.math.imul",
		"es.math.log1p",
		"es.math.log2",
		"es.math.log10",
		"es.math.sign",
		"es.math.sinh",
		"es.math.tanh",
		"es.math.trunc"
	],
	"es.date": ["es.date.now", "es.date.to-iso-string", "es.date.to-json", "es.date.to-primitive", "es.date.to-string"],
	"es.symbol": [
		"es.symbol.async-iterator",
		"es.symbol.has-instance",
		"es.symbol.is-concat-spreadable",
		"es.symbol.iterator",
		"es.symbol.constructor",
		"es.symbol.match",
		"es.symbol.match-all",
		"es.symbol.replace",
		"es.symbol.search",
		"es.symbol.species",
		"es.symbol.split",
		"es.symbol.to-primitive",
		"es.symbol.to-string-tag",
		"es.symbol.unscopables",
		"es.symbol.description"
	],
	"es.collections": ["es.map", "es.weak-map", "es.set", "es.weak-set"],
	"es.typed-array": [
		"es.typed-array.copy-within",
		"es.typed-array.every",
		"es.typed-array.fill",
		"es.typed-array.filter",
		"es.typed-array.find",
		"es.typed-array.find-index",
		"es.typed-array.float32-array",
		"es.typed-array.float64-array",
		"es.typed-array.for-each",
		"es.typed-array.from",
		"es.typed-array.includes",
		"es.typed-array.index-of",
		"es.typed-array.int8-array",
		"es.typed-array.int16-array",
		"es.typed-array.int32-array",
		"es.typed-array.iterator",
		"es.typed-array.join",
		"es.typed-array.last-index-of",
		"es.typed-array.map",
		"es.typed-array.of",
		"es.typed-array.reduce",
		"es.typed-array.reduce-right",
		"es.typed-array.reverse",
		"es.typed-array.set",
		"es.typed-array.slice",
		"es.typed-array.some",
		"es.typed-array.sort",
		"es.typed-array.subarray",
		"es.typed-array.to-locale-string",
		"es.typed-array.to-string",
		"es.typed-array.uint8-array",
		"es.typed-array.uint8-clamped-array",
		"es.typed-array.uint16-array",
		"es.typed-array.uint32-array"
	],
	"es.reflect": [
		"es.reflect.apply",
		"es.reflect.construct",
		"es.reflect.define-property",
		"es.reflect.delete-property",
		"es.reflect.get",
		"es.reflect.get-own-property-descriptor",
		"es.reflect.get-prototype-of",
		"es.reflect.has",
		"es.reflect.is-extensible",
		"es.reflect.own-keys",
		"es.reflect.prevent-extensions",
		"es.reflect.set",
		"es.reflect.set-prototype-of"
	],
	esnext: ["esnext.array", "esnext.collections", "esnext.math", "esnext.number", "esnext.object", "esnext.promise", "esnext.reflect", "esnext.string", "esnext.symbol"],
	"es2016+": ["esnext"],
	"esnext.array": ["es.array.last-index", "es.array.last-item"],
	"esnext.object": [],
	"esnext.collections": ["esnext.map", "esnext.weak-map", "esnext.set", "esnext.weak-set"],
	"esnext.map": [
		"es.map.every",
		"es.map.filter",
		"es.map.find",
		"es.map.find-key",
		"es.map.from",
		"es.map.group-by",
		"es.map.includes",
		"es.map.key-by",
		"es.map.key-of",
		"es.map.map-keys",
		"es.map.map-values",
		"es.map.merge",
		"es.map.of",
		"es.map.reduce",
		"es.map.some",
		"es.map.update",
		"es.map.emplace"
	],
	"esnext.weak-map": ["es.weak-map.from", "es.weak-map.of"],
	"esnext.set": [
		"es.set.add-all",
		"es.set.delete-all",
		"es.set.difference",
		"es.set.every",
		"es.set.filter",
		"es.set.find",
		"es.set.from",
		"es.set.intersection",
		"es.set.join",
		"es.set.map",
		"es.set.of",
		"es.set.reduce",
		"es.set.some",
		"es.set.symmetric-difference",
		"es.set.union",
		"es.set.is-disjoint-from",
		"es.set.is-subset-of",
		"es.set.is-superset-of"
	],
	"esnext.weak-set": ["es.weak-set.from", "es.weak-set.of"],
	"esnext.math": [
		"es.math.clamp",
		"es.math.deg-per-rad",
		"es.math.degrees",
		"es.math.fscale",
		"es.math.iaddh",
		"es.math.imulh",
		"es.math.isubh",
		"es.math.rad-per-deg",
		"es.math.radians",
		"es.math.scale",
		"es.math.signbit",
		"es.math.umulh"
	],
	"esnext.number": ["es.number.from-string"],
	"esnext.promise": ["es.promise.try"],
	"esnext.reflect": [
		"es.reflect.define-metadata",
		"es.reflect.delete-metadata",
		"es.reflect.get-metadata",
		"es.reflect.get-metadata-keys",
		"es.reflect.get-own-metadata",
		"es.reflect.get-own-metadata-keys",
		"es.reflect.has-metadata",
		"es.reflect.has-own-metadata",
		"es.reflect.metadata"
	],
	"esnext.string": ["es.string.at", "es.string.code-points", "es.string.match-all"],
	"esnext.symbol": ["es.symbol.pattern-match"],
	"dom.collections.iterable": ["dom.collections.iterator", "dom.collections.for-each"],
	intl: [
		"intl.date-time-format",
		"intl.display-names",
		"intl.get-canonical-locales",
		"intl.list-format",
		"intl.locale",
		"intl.number-format",
		"intl.plural-rules",
		"intl.relative-time-format"
	],
	animation: ["web-animations"],
	"web-components": ["custom-elements", "shadow-dom", "template"],
	event: ["event.constructor", "event.focusin", "event.hashchange"],
	setimmediate: ["set-immediate"],
	globalthis: ["global-this"],

	// APIs
	"api.constructable-style-sheets": ["api.constructable-stylesheets"],
	"constructable-style-sheets": ["api.constructable-stylesheets"],
	"adopted-style-sheets": ["api.constructable-stylesheets"],

	"performance.now": ["api.performance.now"],
	"performance-now": ["api.performance.now"],
	performance: ["api.performance.now"],

	url: ["api.url"],
	"url-search-params": ["api.url"],

	formdata: ["api.form-data"],
	"form-data": ["api.form-data"],
	"api.formdata": ["api.form-data"],

	console: ["api.console"],

	base64: ["api.base64"],
	atob: ["api.atob"],
	btoa: ["api.base64"],
	"api.atob": ["api.base64"],
	"api.btoa": ["api.base64"],

	blob: ["api.blob"],

	requestidlecallback: ["api.request-idle-callback"],
	"request-idle-callback": ["api.request-idle-callback"],
	"api.requestidlecallback": ["api.request-idle-callback"],

	requestanimationframe: ["api.request-animation-frame"],
	"request-animation-frame": ["api.request-animation-frame"],
	"api.requestanimationframe": ["api.request-animation-frame"],

	// CSS
	"object-fit": ["css.object-fit"],
	"object-position": ["css.object-fit"],
	"css.object-position": ["css.object-fit"],

	// Libs
	systemjs: ["lib.systemjs"],
	"regenerator-runtime": ["lib.regenerator-runtime"]
} as const;

export type PolyfillAlias = typeof POLYFILL_ALIASES;
export type PolyfillAliasedName = ElementOf<typeof POLYFILL_ALIASED_NAME>;
export type PolyfillDealiasedName = ElementOf<typeof POLYFILL_DEALIASED_NAME>;
export type PolyfillName = PolyfillAliasedName | PolyfillDealiasedName;
export type PolyfillNameWithDependencies<Key extends PolyfillName> = Key extends PolyfillAliasedName ? Key | PolyfillNameWithDependencies<ElementOf<PolyfillAlias[Key]>> : Key;
export type PolyfillNameWithMeta = PolyfillNameWithDependencies<keyof PolyfillMeta>;

export const POLYFILL_ALIASED_NAME = new Set(Object.keys(POLYFILL_ALIASES) as (keyof PolyfillAlias)[]);
export const POLYFILL_NAME = new Set([...POLYFILL_DEALIASED_NAME, ...POLYFILL_ALIASED_NAME]);

// This type is used to add type assertions about the keys and values of 'POLYFILL_ALIASES' while
// still leveraging the inference engine of TypeScript
export type AssertsValidPolyfillAliases<T extends {[Key in PolyfillAliasedName]: readonly PolyfillName[]} = PolyfillAlias> = T;
